### ISSUE TITLE
Supporting freestanding for many implementations might be unfeasible or undesirable

### ISSUE THREAD

**Issue by matu3ba** [ziglang/universal-headers#2]
Semantics of freestanding are insufficient as the C standard (is intentially) underspecific on behavior of IO functions in the context of non-hosted environments. To quote an exaggaration from https://thephd.dev/conformance-should-mean-something-fputc-and-freestanding:
```
"fread is not part of freestanding C, and we ship a freestanding implementation, 
so we can do whatever we want to the I/O functions. Sorry!"
```

**Comment by andrewrk** [comment]
OK
